### ISSUE TITLE
Is this an actual book too?

### ISSUE THREAD

**Issue by pickhardt** [clinical-meteor/software-development-kit#79]
I saw a book on Amazon and just want to check, is this repo related to the following book:

http://www.amazon.com/Meteor-Web-Application-Development-Cookbook/dp/1783280298/ref=tmm_pap_title_0?_encoding=UTF8&sr=&qid=

**Comment by rhyslbw** [comment]
https://forums.meteor.com/t/meteor-cookbook-released/5074

**Comment by awatson1978** [comment]
No, it's something else.  I've been doing the Meteor Cookbook for neatly three years.  Packt came out with their own cookbook a couple of months ago.  It's been something of an attempt at an aggressive takeover.

Trivia fact:  that's actually the fourth Meteor Cookbook (mine is the third).  The were two other attempts before mine, but they each only managed a handful of recipes before being abandoned.

I've been thinking of maybe rebranding the meteor-cookbook repository into a framework, since that's what it's started becoming in the past year.  Maybe just rename to Clinical Meteor, now that other people are attempting to manage the Meteor Cookbook namespace.

**Comment by awatson1978** [comment]
Meteor Cookbook is being migrated to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/topics?page=2&tab=popular); in part due to Packt moving into this space.  Meteor Cookbook is being deprecated.
